/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface StCachedImage {
      'errorHolder': string;
      'placeHolder': string;
      'src': string;
    }
  }

  interface HTMLStCachedImageElement extends StencilComponents.StCachedImage, HTMLStencilElement {}

  var HTMLStCachedImageElement: {
    prototype: HTMLStCachedImageElement;
    new (): HTMLStCachedImageElement;
  };
  interface HTMLElementTagNameMap {
    'st-cached-image': HTMLStCachedImageElement;
  }
  interface ElementTagNameMap {
    'st-cached-image': HTMLStCachedImageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-cached-image': JSXElements.StCachedImageAttributes;
    }
  }
  namespace JSXElements {
    export interface StCachedImageAttributes extends HTMLAttributes {
      'errorHolder'?: string;
      'placeHolder'?: string;
      'src'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;